### ISSUE TITLE
How to generate prep_data.pkl of Lorel

### ISSUE THREAD

**Issue by Liang-ZX** [Div99/LISA#2]
Hi,

It seems that there are not pkl file in Lorel dataset. And how to generate "prep_data.pkl". Besides, how to merge labels.csv to it? The lanuage labels have too many "do nothing" annotations. Thank you.

Looking forward to your reply.

**Comment by Liang-ZX** [comment]
Solved.

**Comment by siifish** [comment]
Hi,
It seems that I met the same problem. Fortunately, you have solved it. Can you share your solution? 
Thanks a lot! Looking forward to your reply.
