### ISSUE TITLE
Expert dataset for babyai

### ISSUE THREAD

**Issue by Acedorkz** [Div99/LISA#3]
Hi there,

It seems an interesting work. But I can not find '/atlas/u/divgarg/datasets/babyai/demos_iclr19_v2/BabyAI-GoToSeq-v0.pkl', could u please give me some hints? Thanks a lot.

**Comment by siifish** [comment]
Hi, it seems that I met the same problem, did you find out the solution yet?

**Comment by skandavaidyanath** [comment]
Hi! Thank you for your interest in this work! The BabyAI datasets can be downloaded from here: https://drive.google.com/drive/folders/124DhBJ5BdiLyRowkYnVtfcYHKre9ouSp
More details are in the original BabyAI repo: https://github.com/mila-iqia/babyai/tree/iclr19
